export const LEVELS = {
    levels: [
        {
            width: 4,
            height: 4,
            startPosition: [0, 0],
            finishPosition: [3, 3],
            holePositions: [
                [1, 1],
                [3, 1],
                [3, 2],
                [0, 3],
            ],
        },
        {
            width: 6,
            height: 6,
            startPosition: [0, 0],
            finishPosition: [5, 5],
            holePositions: [
                [2, 0],
                [5, 0],
                [1, 1],
                [3, 2],
                [2, 3],
                [4, 4],
                [1, 5],
                [4, 5],
            ],
        },
        {
            width: 10,
            height: 6,
            startPosition: [0, 2],
            finishPosition: [9, 0],
            holePositions: [
                [2, 0],
                [4, 0],
                [6, 0],
                [8, 0],
                [4, 1],
                [8, 1],
                [2, 2],
                [4, 2],
                [8, 2],
                [2, 3],
                [4, 3],
                [6, 3],
                [2, 4],
                [6, 4],
                [8, 4],
                [2, 5],
                [4, 5],
                [6, 5],
            ],
        },
        {
            width: 11,
            height: 10,
            startPosition: [0, 0],
            finishPosition: [5, 4],
            holePositions: [
                [2, 2],
                [3, 2],
                [4, 2],
                [5, 2],
                [6, 2],
                [7, 2],
                [8, 2],
                [2, 3],
                [8, 3],
                [2, 4],
                [4, 4],
                [6, 4],
                [8, 4],
                [2, 5],
                [4, 5],
                [5, 5],
                [6, 5],
                [8, 5],
                [2, 6],
                [8, 6],
                [2, 7],
                [3, 7],
                [7, 7],
                [8, 7],
            ],
        },
    ],
};